### ISSUE TITLE
DB: better reviews dbs

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/support#129]
create new create db/secret process (current art in kosko-charts/azure-pg)

https://hackmd.io/@5eaaFGMWTfeaTaAsl2Q3OQ/ryQAIWtut

**Comment by devthejo** [comment]
related to:
https://github.com/SocialGouv/actions/pull/58
https://github.com/SocialGouv/kosko-charts/pull/826
https://github.com/SocialGouv/actions/pull/57
https://github.com/SocialGouv/docker/pull/910
https://github.com/SocialGouv/kosko-charts/pull/828

**Comment by devthejo** [comment]
reste à tester l'implémentation ;-)
et à éventuellement debugger le cas échéant

**Comment by revolunet** [comment]
Merci @devthejo 

Les actions : je pense qu'elles ne devraient pas s'appuyer sur un éventuel dossier `.k8s` dans le repo du projet mais être autonomes, donc installer kosko-charts, lequel intègrerait les jobs en question. 

Question `create-db-secret` : pourquoi faire le kubectl apply depuis l'image docker alors qu'on pourrait générer le password et le secret et le sealer dans kosko-charts au moment de l'execution du job ? c'est pour isoler la dépose du secret de son usage dans kosko-charts ?

**Comment by devthejo** [comment]
- les jobs seront intégrés dans kosko-charts par cette PR: https://github.com/SocialGouv/kosko-charts/pull/828
ensuite il faut simplement les appeler mais effectivement par un call depuis .k8s, je n'ai pas vu d'exemple d'implémentation où on appelle directement une kosko chart par une gh action sans aucune activation depuis .k8s.

- Yep, en fait pas besoin de sealer le secret, cela me semblait finalement beaucoup plus compliqué (et également moins propre) que nécessaire, on le génère de manière aléatoire dans le job et ensuite on l'appelle aussi bien dans le job qui créé la db et le user que dans les déploiements.

**Comment by devthejo** [comment]
de plus, si on me le secret (sealed) dans un manifest, il va écraser le précédent à chaque fois, hors là, le job vérifie qu'il n'y a pas déjà un secret, et seulement si il n'y en a pas il le créé

**Comment by revolunet** [comment]
> 



> * les jobs seront intégrés dans kosko-charts par cette PR: [feat(pg): create-db-secret + create-db-user kosko-charts#828](https://github.com/SocialGouv/kosko-charts/pull/828)
>   ensuite il faut simplement les appeler mais effectivement par un call depuis .k8s, je n'ai pas vu d'exemple d'implémentation où on appelle directement une kosko chart par une gh action sans aucune activation depuis .k8s.

Ok super, en effet il reste à voir comment executer ces jobs sans dépendance au projet

> * Yep, en fait pas besoin de sealer le secret, cela me semblait finalement beaucoup plus compliqué (et également moins propre) que nécessaire, on le génère de manière aléatoire dans le job et ensuite on l'appelle aussi bien dans le job qui créé la db et le user que dans les déploiements.

Ok, sounds good !

**Comment by revolunet** [comment]
Proposition sur comment faire pour executer ces jobs :

On a un dossier ["template autodevops" sur kosko-charts](https://github.com/SocialGouv/kosko-charts/tree/master/templates/autodevops) qui peut-être degité puis exécuté directement comme [ici par exemple](https://github.com/SocialGouv/actions/blob/master/autodevops-manifests/action.yml#L30). En intégrant tes jobs dans ce template, on pourrait `kosko generate` ces jobs individuellement.

On se cale une visio pour échanger la dessus ou autre idée ?

**Comment by devthejo** [comment]
related to:
https://github.com/SocialGouv/actions/pull/62

**Comment by devthejo** [comment]
reste à merger:
https://github.com/SocialGouv/kosko-charts/pull/828
https://github.com/SocialGouv/actions/pull/62

puis à tester en utilisant la branch [devthejo/create-db sur sample-next-app](https://github.com/SocialGouv/sample-next-app/tree/devthejo/create-db)
ou en la mergeant depuis la PR https://github.com/SocialGouv/sample-next-app/pull/561

note: upgrader la version de kosko-charts intégrant les derniers changements (dès qu'elle sera released) avant de merger la PR sur sample-next-app (ce qui devrait également fixer l'erreur de testing dans l'action :-))

**Comment by devthejo** [comment]
related to:
https://github.com/SocialGouv/actions/pull/63

**Comment by devthejo** [comment]
Hourra !
https://github.com/SocialGouv/sample-next-app/pull/562

**Comment by revolunet** [comment]
pour terminer sur ce sujet, il reste quoi a part :

 - pouvoir désactiver la creation de db dans kosko-charts
 - modifier les workflows pour ajouter l'action `create-db`

**Comment by revolunet** [comment]
? https://github.com/SocialGouv/carnets/commits/beta

**Comment by revolunet** [comment]
Je ferme puisque c'est dispo ici : https://github.com/SocialGouv/actions/blob/master/autodevops-create-db/

![](https://media.giphy.com/media/Q99kEQFAWElfQ1bfcQ/giphy-downsized-large.gif)
