### ISSUE TITLE
Scaleway : Utilisation de PG

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/support#139]
- [ ] Valider l'utilisation des PG Scaleway : 
   - [ ] Performances/stabilité
   - [ ] Sécurité des backups
   - [ ] Procédures de backup/restore
   - [x] Sécurité de la connexion réseau
   - [ ] QUID Grafana/psql pour les devs
   - [x] RGPD : deja pour le dev ?
   - [x] Check SSL &check;

- [ ] Modifier la CI de create db

**Comment by revolunet** [comment]
Le SSL est un certificat self-signed

**Comment by devthejo** [comment]
du coup il faut qu'on importe leur root certificate j'imagine...
