### ISSUE TITLE
Helm-charts Apps statiques

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/support#162]
v0 : apps statiques

 - utiliser le Dockerfile du projet
 - possibilité d'override le hostname de prod
 - possibilité d'ajuster les annotations de l'ingress

Comment donner du feedback au dev lors d'un deploy ?

**Comment by devthejo** [comment]
autodevops-helm static apps in progress:
[x] standup
[x] www
[x] emjpm-portail
[...presque] archifiltre-site
[ ] monsuivipsy-site
[ ] ozensemble-site
[ ] nos1000jours-landing
[ ] 1000jours-blues
[ ] nos1000jours-blues-epds-pro
[ ] nos1000jours-blues-epds-widget
[ ] siret2idcc
[ ] serving-ml (hpa)
[ ] template
