### ISSUE TITLE
testing actions/helm

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/support#177]
ajouter des snapshots et/ou tests des actions

**Comment by devthejo** [comment]
https://github.com/SocialGouv/actions/tree/master/autodevops-helm-deploy/tests
;)

**Comment by revolunet** [comment]
Comment ajouter d'autres cas ?

**Comment by devthejo** [comment]
je me disais qu'on allait étoffer ce cas d'un maximum de paramètres, mais effectivement, il serait bien d'avoir plusieurs dossiers dans tests, qui reprennent le contenu de celui actuel, on pourrait changer les variables d'env dans le point script sh et le contenu dans chaque sous dossier .socialgouv, j'intègre ça dans le nouveau dépôt avec un script central qui les lance tous
