### ISSUE TITLE
GithubLess

### ISSUE THREAD

**Issue by devthejo** [SocialGouv/support#192]
- MEP without github (solution: webhook + any other git service: gitlab/gitea etc...)
- OAuth
  - Rancher
  - Sentry
  - Matomo
  - NextCloud
  - Pastek (/Zammad)
  - Secretariat
  - Carnets
- Team Management
  - terraform
  - ... ?

**Comment by revolunet** [comment]
documenter le CLI + webhook dans une doc SRE ?
