### ISSUE TITLE
Code source

### ISSUE THREAD

**Issue by gary-van-woerkens** [SocialGouv/support#194]

**Comment by revolunet** [comment]
https://github.com/SocialGouv/support/issues/240

**Comment by revolunet** [comment]
https://github.com/josegonzalez/python-github-backup

**Comment by revolunet** [comment]
implémenté dans https://github.com/SocialGouv/manifests/pull/54

 - Cronjob quotidien
 - Utilise le cluster scaleway + un volume scaleway (75€/To/mois)

1ere synchro lancée, a voir comment ca fonctionne

**Comment by revolunet** [comment]
a priori c'est réglé, MaxEmilien va repasser dessus pour verif
