### ISSUE TITLE
sealed secrets linter

### ISSUE THREAD

**Issue by gary-van-woerkens** [SocialGouv/support#204]
Exposer `/v1/verify` pour pouvoir valider un secret.

**Comment by revolunet** [comment]
fait côté OPs; exemple d'usage : https://gist.github.com/revolunet/c07732162add17fcd4254c517cdbbc39

a voir : est-ce qu'on intègre un check dans notre CI pour vérifier les secrets avant déploiement. je dirai que oui :)

**Comment by revolunet** [comment]
https://github.com/bitnami-labs/sealed-secrets/issues/870

**Comment by devthejo** [comment]
will be fixed by https://github.com/bitnami-labs/sealed-secrets/pull/873

**Comment by revolunet** [comment]
opérationnel en dev/prod
