### ISSUE TITLE
Problème Tipimail / DKIM

### ISSUE THREAD

**Issue by gary-van-woerkens** [SocialGouv/support#205]

**Comment by revolunet** [comment]
Point mercredi 22 à 14h30

**Comment by gary-van-woerkens** [comment]
Comment autoriser les domaines des produits ?
Faut-il demander au OPS d'effectuer la configuration pour chaque domaine de chaque produit.

**Comment by igorrenquin** [comment]
`Comment autoriser les domaines des produits ?` j'ai pas compris ta question

Quand des actions sont à réaliser sur des domaines gérés par le MCAS (exemple: travail.gouv.fr, santé.gouv.fr) il faut ouvrir une demande sur l'outil de support de la DNUM en leur communiquant les informations nécessaires.

Dans le cas ou la FabNum gére les domaines les actions se partagent entre les personnes qui ont les droits

**Comment by revolunet** [comment]
Est-ce qu'on a quelque chose de documentable sur le process à réaliser pour les startups, par exemple la config tipimail ?

**Comment by revolunet** [comment]
Exemple avec le compte tipimail "secretariat" qui n'a pas de domaine configuré :

![Image](https://user-images.githubusercontent.com/124937/183663913-2528bbeb-c05c-4c30-a080-8c591989c647.png)

**Comment by revolunet** [comment]
![Image](https://user-images.githubusercontent.com/124937/183903523-e42974c6-7d5e-4057-b48b-b5a83ea13329.png)

![Image](https://user-images.githubusercontent.com/124937/183903571-621915ba-039e-4f3e-a988-95871e14ee77.png)

Ce qu'on peut faire pour améliorer :
 - voir comment activer le DMARC

Pour ce qui est des domaine tiers, je ne sais pas s'il y a quelque chose de documentable

**Comment by revolunet** [comment]
fixed by @igorrenquin

**Comment by igorrenquin** [comment]
info sur DKIM et l'offre OVH email pro

https://community.ovh.com/t/configurer-dkim-sur-ovh-email-pro/19517
