### ISSUE TITLE
Create DB

### ISSUE THREAD

**Issue by gary-van-woerkens** [SocialGouv/support#215]
- Automatiser la création de DBs et des secrets
- Pouvoir créer une base de prod/preprod

*exemple*: base de prod de l'app, base de prod du metabase ou keycloak de l'app...

- Chaque équipe peut avoir autant de bases de preprod/prod que nécessaire

p-e dans le repo manifests ?

**Comment by revolunet** [comment]
une approche possible : https://github.com/SocialGouv/manifests/blob/37bff8e062b368533d3999351bce88da18304177/.github/workflows/create-db.yml

**Comment by devthejo** [comment]
développements en cours sur kontinuous pour permettre à la solution proposée de fonctionner

**Comment by revolunet** [comment]
solution minimale implémentée pour l'instant : création des DBS via l'UI des actions GitHub.

Puis on récupére le secret pour le poser dans le repo /manifests avec un script commt exemple.

**Comment by revolunet** [comment]
Yay, big up @devthejo 

![Image](https://user-images.githubusercontent.com/124937/175519454-1ac25b0a-881e-4c84-992e-bec716c8144a.png)
![Image](https://user-images.githubusercontent.com/124937/175519453-82818137-9de4-4d49-be3c-4cbd120c3ce6.png)
