### ISSUE TITLE
Développement de Kontinuous

### ISSUE THREAD

**Issue by gary-van-woerkens** [SocialGouv/support#224]

**Comment by devthejo** [comment]
- [ ] refacto
- [ ] tests
- [ ] tests comparatifs de snapshots sur les repos
- [ ] documentation
  - [ ] implémentation utilisateurs
  - [ ] écriture de plugins
  - [ ] pour les devs
- [ ] migration de tous les repos

**Comment by devthejo** [comment]
see https://github.com/SocialGouv/kontinuous/issues

**Comment by devthejo** [comment]
TODO
- [] terminer de créer les issues
- [] traiter les issues
