### ISSUE TITLE
Git Backups

### ISSUE THREAD

**Issue by gary-van-woerkens** [SocialGouv/support#225]
- [ ] Synchronisation Github/Gitlab avec `BeegBro`.

**Comment by revolunet** [comment]
duplicate #194 ?

**Comment by devthejo** [comment]
https://github.com/josegonzalez/python-github-backup

plutôt à classer dans Disaster recovery

**Comment by revolunet** [comment]
Remplacé par #194

**Comment by revolunet** [comment]
PR de max à venir
