### ISSUE TITLE
[STANDUP] Supprimer les teams FCE et eMJPM

### ISSUE THREAD

**Issue by gary-van-woerkens** [SocialGouv/support#227]
Il me semble qu'on ne peut plus retirer les slides du **Standup** facilement.

- Pour retirer une team du Standup il faut changer la visibilité de cette team.
- Changer la visibilité d'une team Github implique que cette dernière n'ait pas de sous-team.
- Notre *infra as code* ajoute des sous-teams `Admin` par défaut à chaque team Github.

Est-ce qu'il faut supprimer la référence a la team dans notre *infra as code* pour retirer des slides du **Standup** ?

**Comment by revolunet** [comment]
looks good : https://github.com/SocialGouv/standup/blob/master/src/utils/slides.js#L25
