### ISSUE TITLE
[DOC]: best practices data modeling

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/support#237]
- insister sur l'importance d'un bon modèle de données
 - pérennité du back/API VS frontends
 - outillage pour documenter/dumper les schemas de DB
 - conventions dans les APIs / modèles de données
 - best practices Postgres

**Comment by devthejo** [comment]
outils de créations de diagrams ERM from scratch:
- draw.io
- yEd

retro diagram from existing DB:
- DBeaver

**Comment by revolunet** [comment]
a discuter : https://github.com/SocialGouv/support/pull/263

**Comment by revolunet** [comment]
fixed in https://socialgouv.github.io/support/#/databases

**Comment by revolunet** [comment]
fixed in https://socialgouv.github.io/support/#/databases
