### ISSUE TITLE
feat(github): Sauvegarde-clone des repo hors de github

### ISSUE THREAD

**Issue by igorrenquin** [SocialGouv/support#240]
# Contexte

Pour limiter le risque de dépendance avec les produits soumis hors EU. Il est demandé d'être en capacité de fonctionné sans github.

# Démarche de résolution

Mettre en place au niveau de l'organisation github un workflow unique qui permettra de recopier le code des produits vers un repo `miroir` sur giltab

# DOD
- Etudier la possibilité de mise en place :
  - au niveau de l'organisation github un workflow qui permettrai de recopier le code des produits vers un repo `miroir` sur giltab
  - Identifier les événements les plus appropriés pour lancer l'action de synchronisation ( comit,autre, ...) 
- Créer une tâche de mise en place de la synchronisation des repo github -> gitlab

**Comment by revolunet** [comment]
voir aussi https://github.com/SocialGouv/support/issues/240

**Comment by revolunet** [comment]
duplicate de #194
