### ISSUE TITLE
[DOMIFA] Supprimer les ressources inutiles (DBs, storages...)

### ISSUE THREAD

**Issue by gary-van-woerkens** [SocialGouv/support#246]
On peut deja s'occuper des éléménts suivants:
- [ ] Anciennes bases de données (non flex)
- [ ] Storages accounts (pour l'upload de fichiers: volumes montés sur les pods)

**Comment by achauve** [comment]
- Voir lequel supprimer en volumes : prod ou prod2
- côté DB on est ok

**Comment by revolunet** [comment]
storage utilisé en prod : prod2

**Comment by achauve** [comment]
@revolunet est-ce que tu supprimes le prod tout court ?

**Comment by achauve** [comment]
@revolunet on peut clore l'issue tu penses ? je crois qu'on avait tout supprimé

**Comment by achauve** [comment]
Je rouvre le ticket, le stockage a l'air d'être toujours dans terraform (https://gitlab.fabrique.social.gouv.fr/infra/infra-startup/-/tree/master/domifa/prod/storage-account-domifaprod) et il faudrait le supprimer.

**Comment by achauve** [comment]
@octomir c'est bien domifaprod https://gitlab.fabrique.social.gouv.fr/infra/infra-startup/-/tree/master/domifa/prod/storage-account-domifaprod qu'il faut supprimer. Il est toujours dans terraform mais a priori a déjà été supprimé dans Azure.

**Comment by octomir** [comment]
> @octomir c'est bien domifaprod https://gitlab.fabrique.social.gouv.fr/infra/infra-startup/-/tree/master/domifa/prod/storage-account-domifaprod qu'il faut supprimer. Il est toujours dans terraform mais a priori **a déjà été supprimé dans Azure.**

je vois une resource dans azure qui sera supprimé 
https://domifaprod.blob.core.windows.net
`  # azurerm_storage_account.this will be destroyed
  - resource "azurerm_storage_account" "this" {
      - account_kind                   = "Storage" -> null
      - account_replication_type       = "LRS" -> null
      - account_tier                   = "Standard" -> null
      - allow_blob_public_access       = false -> null
      - enable_https_traffic_only      = true -> null
      - id                             = "/subscriptions/27c6b463-3e60-4b03-be7f-98a64d49bebd/resourceGroups/backup_prod-stack/providers/Microsoft.Storage/storageAccounts/domifaprod" -> null
      - is_hns_enabled                 = false -> null
      - location                       = "francecentral" -> null
      - min_tls_version                = "TLS1_0" -> null
      - name                           = "domifaprod" -> null
      - nfsv3_enabled                  = false -> null
      - primary_access_key             = (sensitive value)
      - primary_blob_connection_string = (sensitive value)
      - primary_blob_endpoint          = "https://domifaprod.blob.core.windows.net/" -> null
      - primary_blob_host              = "domifaprod.blob.core.windows.net" -> null
      - primary_connection_string      = (sensitive value)
      - primary_file_endpoint          = "https://domifaprod.file.core.windows.net/" -> null
      - primary_file_host              = "domifaprod.file.core.windows.net" -> null
      - primary_location               = "francecentral" -> null
      - primary_queue_endpoint         = "https://domifaprod.queue.core.windows.net/" -> null
      - primary_queue_host             = "domifaprod.queue.core.windows.net" -> null
      - primary_table_endpoint         = "https://domifaprod.table.core.windows.net/" -> null
      - primary_table_host             = "domifaprod.table.core.windows.net" -> null
      - queue_encryption_key_type      = "Service" -> null
      - resource_group_name            = "backup_prod-stack" -> null
      - secondary_access_key           = (sensitive value)
      - secondary_connection_string    = (sensitive value)
      - shared_access_key_enabled      = true -> null
      - table_encryption_key_type      = "Service" -> null
      - tags                           = {} -> null

      - blob_properties {
          - change_feed_enabled      = false -> null
          - last_access_time_enabled = false -> null
          - versioning_enabled       = false -> null
        }

      - network_rules {
          - bypass                     = [
              - "AzureServices",
            ] -> null
          - default_action             = "Allow" -> null
          - ip_rules                   = [] -> null
          - virtual_network_subnet_ids = [] -> null
        }

      - queue_properties {

          - hour_metrics {
              - enabled               = true -> null
              - include_apis          = true -> null
              - retention_policy_days = 7 -> null
              - version               = "1.0" -> null
            }

          - logging {
              - delete                = false -> null
              - read                  = false -> null
              - retention_policy_days = 0 -> null
              - version               = "1.0" -> null
              - write                 = false -> null
            }

          - minute_metrics {
              - enabled               = false -> null
              - include_apis          = false -> null
              - retention_policy_days = 0 -> null
              - version               = "1.0" -> null
            }
        }

      - timeouts {}
    }

  # azurerm_storage_share.share["database"] will be destroyed
  - resource "azurerm_storage_share" "share" {
      - enabled_protocol     = "SMB" -> null
      - id                   = "https://domifaprod.file.core.windows.net/database" -> null
      - metadata             = {} -> null
      - name                 = "database" -> null
      - quota                = 1 -> null
      - resource_manager_id  = "/subscriptions/27c6b463-3e60-4b03-be7f-98a64d49bebd/resourceGroups/backup_prod-stack/providers/Microsoft.Storage/storageAccounts/domifaprod/fileServices/default/fileshares/database" -> null
      - storage_account_name = "domifaprod" -> null
      - url                  = "https://domifaprod.file.core.windows.net/database" -> null

      - timeouts {}
    }

  # azurerm_storage_share.share["domifa-backup-restore"] will be destroyed
  - resource "azurerm_storage_share" "share" {
      - enabled_protocol     = "SMB" -> null
      - id                   = "https://domifaprod.file.core.windows.net/domifa-backup-restore" -> null
      - metadata             = {} -> null
      - name                 = "domifa-backup-restore" -> null
      - quota                = 128 -> null
      - resource_manager_id  = "/subscriptions/27c6b463-3e60-4b03-be7f-98a64d49bebd/resourceGroups/backup_prod-stack/providers/Microsoft.Storage/storageAccounts/domifaprod/fileServices/default/fileshares/domifa-backup-restore" -> null
      - storage_account_name = "domifaprod" -> null
      - url                  = "https://domifaprod.file.core.windows.net/domifa-backup-restore" -> null

      - timeouts {}
    }

  # azurerm_storage_share.share["domifa-export-anonymized"] will be destroyed
  - resource "azurerm_storage_share" "share" {
      - enabled_protocol     = "SMB" -> null
      - id                   = "https://domifaprod.file.core.windows.net/domifa-export-anonymized" -> null
      - metadata             = {} -> null
      - name                 = "domifa-export-anonymized" -> null
      - quota                = 128 -> null
      - resource_manager_id  = "/subscriptions/27c6b463-3e60-4b03-be7f-98a64d49bebd/resourceGroups/backup_prod-stack/providers/Microsoft.Storage/storageAccounts/domifaprod/fileServices/default/fileshares/domifa-export-anonymized" -> null
      - storage_account_name = "domifaprod" -> null
      - url                  = "https://domifaprod.file.core.windows.net/domifa-export-anonymized" -> null

      - timeouts {}
    }

  # azurerm_storage_share.share["files"] will be destroyed
  - resource "azurerm_storage_share" "share" {
      - enabled_protocol     = "SMB" -> null
      - id                   = "https://domifaprod.file.core.windows.net/files" -> null
      - metadata             = {} -> null
      - name                 = "files" -> null
      - quota                = 10 -> null
      - resource_manager_id  = "/subscriptions/27c6b463-3e60-4b03-be7f-98a64d49bebd/resourceGroups/backup_prod-stack/providers/Microsoft.Storage/storageAccounts/domifaprod/fileServices/default/fileshares/files" -> null
      - storage_account_name = "domifaprod" -> null
      - url                  = "https://domifaprod.file.core.windows.net/files" -> null

      - timeouts {}
    }

Plan: 0 to add, 0 to change, 5 to destroy.
`

**Comment by octomir** [comment]
Petite confirmation ou MAJ de l'action en cours SVP

**Comment by revolunet** [comment]
donc : 
 - le storage `domifaprod` peut être supprimé
 - le storage `domifaprod2` doit être conservé
      - les shares `domifa-backup-restore` et `domifa-export-anonymised` peuvent être supprimés

**Comment by revolunet** [comment]
https://gitlab.fabrique.social.gouv.fr/infra/infra-startup/-/merge_requests/224
