### ISSUE TITLE
debt: dead project should be archived or deleted 

### ISSUE THREAD

**Issue by douglasduteil** [SocialGouv/support#25]
We should add a comment in the readme with :skull: for archived repos (see https://github.com/SocialGouv/work-in-france-bo-public/blob/master/README.md)

Targets:

- [x] https://github.com/SocialGouv/cors-anywhere
      https://gitlab.factory.social.gouv.fr/SocialGouv/cors-anywhere

**Comment by revolunet** [comment]
to DELETE (no value) : 

 - [ ]  https://github.com/SocialGouv/code-du-travail-data
 - [ ]  https://github.com/SocialGouv/code-du-travail-api
 - [ ]  https://github.com/SocialGouv/code-du-travail-css
 - [ ] https://github.com/SocialGouv/annuaire-mjpm 
 - [ ] https://github.com/SocialGouv/UDD
 - [ ] https://github.com/SocialGouv/code-du-travail-monitoring
 - [ ] https://github.com/SocialGouv/template.data.gouv.fr.react
 - [ ] https://github.com/SocialGouv/code-du-travail-chatbot

**Comment by douglasduteil** [comment]
Merci @revolunet :+1: :skull: :+1:

**Comment by revolunet** [comment]
céréales killer
