### ISSUE TITLE
Update des images nginx:7.0.0 et nginx4spa:7.0.0 vers 7.0.1

### ISSUE THREAD

**Issue by gary-van-woerkens** [SocialGouv/support#250]

**Comment by revolunet** [comment]
https://github.com/search?l=Dockerfile&q=org%3ASocialGouv+%22nginx%3A7.0.0%22&type=Code

**Comment by octomir** [comment]
# Image Security update
Mise a jour d'image container nginx et nginx4spa:7.0.0 pour réduire considérablement les vulnérabilité

**Comment by revolunet** [comment]
je commence les pr
