### ISSUE TITLE
Accès aux backups de prod

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/support#253]
A voir comment on traite les demandes récurrentes d'accès aux DBs de prod

Idées : 
 - granter l'accès aux bons backups aux membres de la team "Admins xxx" sur GitHub
 - fournir un endpoint où ils peuvent récupérer les n derniers dumps
 - logger les acces

**Comment by revolunet** [comment]
Possibilité :

Un service web qui :
 - oauth la team GH (via oauth2-proxy?)
 - permet de download le dump de la bonne team
 
 Difficultés :
  - identifier à quels storages de backup a accès quel team admin GH

**Comment by maxgfr** [comment]
+1

**Comment by revolunet** [comment]
Idées : 

 - utiliser l'image d'un "filebrowser" existant ([exemple](https://hub.docker.com/r/filebrowser/filebrowser))
 - créer un Pod avec un montage vers le storage de backup
 - stocker dans le repo /manifests les secrets + mapping team/secrets
 - créer des apps argo pour chaque team a déployer
 
 Ce service pourra être exposé via `oauth2-proxy` pour limiter l'accès aux teams admins
 
```mermaid
graph LR

internet-->oauth2[oauth2-proxy]
oauth2-->github
oauth2-->filebrowser[filebrowser]
filebrowser-->|secret|azure[volume azure]

```

**Comment by revolunet** [comment]
1ère étape : identifier le filebrowser qui pourrait faire le job, ca peut se tester en local. il faudrait limiter les droits à lecture/download

**Comment by revolunet** [comment]
pour l'instant on s'est dit que c'est un peu trop touchy niveau sécu vs le cout de le faire manuellement
