### ISSUE TITLE
renovate: lighter

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/support#27]
J'ai plusieurs retours de souffrance sur l'ami renovate, que je partage

**Constat :**
 - c'est pénible et chronophage à gérer au quotidien côté dev
 - les équipes ne maitrisent pas toujours la config renovate et donc la subissent
 - charge induite sur la CI
 - notifications nombreuses entre les PR et retours de pipeline

**Solutions proposées :**
 - faire une config renovate-light
     - autoMerge des patches
     - PR mensuelle groupée pour le reste
 - ajouter dans [la FAQ du support](https://socialgouv.github.io/support/#/faq) les infos de base pour que les équipes puissent mieux comprendre le fonctionnement et le tweaker. comment upgrade manuellement tel ou tel package (cli)...

**Comment by tglatt** [comment]
dans le cas d'`emjpm`, la solution proposée est bonne. Cela permettra de ne pas s'occuper des patches et d'avoir une notification une fois par mois sur les maj possibles. On décidera alors au sein de l'équipe d'appliquer ou pas.

**Comment by lionelB** [comment]
si vous avez besoin d'aide pour tweakez la config je peux aider

**Comment by pom421** [comment]
Mon expérience de rookie, c'est qu'effectivement, c'est plutôt très pénible (et limite anxiogène ;)) le fonctionnement actuel, avec 1 PR/branche par changement trouvé. Une semaine après avoir upgradé mon projet, je me retrouve avec 10 PR. D'ailleurs, la dernière fois où j'ai update les libs, j'ai préféré faire un `yarn upgrade` global et vérifier que ça marche.

Côté solutions, faire 1 PR pour les upgrades non patchs me paraît bien. Mais la solution précise 1 par mois. Si je laisse passer 3 mois sans rien faire, on se retrouverait avec 3 PR à merge? Est-ce que faire 1 PR qui stocke tout, jusqu'à ce qu'on merge manuellement, serait pas plus simple ?

Pour le merge auto des patchs, je suis un peu mitigé. Est-ce que l'automerge, va jusqu'à une nouvelle MEP si les tests lancés par le CI sont bons?

**Comment by lionelB** [comment]
tu peux grouper major / minor / patch  dans une seule pr qui tourne tout les mois et tu fermes la pr ou la laisse ouverte 3mois, renovate la mettra a jour chaque mois

**Comment by revolunet** [comment]
Pour l'automerge des patches qui part directement en prod ou pas, ca dépend du "workflow" GIT

Soit les releases sont obligatoires pour aller en prod, et donc il faut faire une release pour y intégrer les patchs.

Soit on est dans tu merge to master = prod, soit déploiement continu et là ca pourrait être intégré automatiquement. Mais pour ca il faut une bonne couverture de test...

**Comment by gary-van-woerkens** [comment]
Mon expérience de Renovate est assez mince et j'ai bon espoir qu'une configuration adaptée puisse résoudre la situation évoquée, qui m'impacte aussi.

Il se trouve que j'ai récemment eu des soucis avec des mises à jour de patches sur `moment`, `prettier` et `victory`. Et j'aimerai ne pas voir ces changements passer en prod automatiquement sans pour autant perdre la fonctionnalité `merge to master = prod`.

Concernant les tests, il me parait peu probable d'obtenir une couverture permettant une sécurisation "convenable" des mises à jour des dépendances de tout un projet.

De plus, tester certaines dépendances comme `prettier` n'a pas vraiment de sens. Pour autant, se retrouver avec un `eslint/prettier` non fonctionnel quand on s'apprête à traiter un problème de production, dont on aimerait la résolution simple et rapide, peut être assez pénible.

Je préfere garder la main sur le séquencement des soucis auxquels je dois faire face, tant que faire se peut... meme s'ils sont inéluctables :)

**Comment by revolunet** [comment]
je suis très curieux d'en savoir plus sur le patch foireux de moment.js :)
cette librairie est over-used

j'en profite pour faire la promo de [date-fns](https://date-fns.org/) qui est plus light et ne fait pas de mutation sur les dates

**Comment by Toub** [comment]
Renovate est un outil, il est donc pas mal de savoir quels sont les objectifs derrière.

Par exemple:
- appliquer le plus rapidement possible les patchs de sécurité
- se tenir un minimum à jour (dette technique, branche maintenue...)
- tendre à uniformiser les versions sur les projets SocialGouv

Face à ça, il y a le coût:
- appliquer automatiquement les mises à jour patch via 1 seule PR hebdomadaire (voir quotidienne), ça ne coûte pas grand chose, alors pourquoi ne pas le faire?
- pour les mises à jour mineures, il est quand même pas mal de jeter un coup d'oeil rapide au changes log pour ne pas rater des nouveautés intéressantes (en tout cas pour les packages que l'on utilise directement)
- pour les mises à jour majeures, c'est à voir au cas par cas, et c'est parfois très coûteux, donc à voir en fonction des besoins et priorités du projet

En conclusion, ce que tu proposes semble pas mal du tout, y compris la page de faq.

**Comment by Toub** [comment]
Question, est-il possible (et pertinent) d'intégrer dans la config renovate des recommandations de version communes à SocialGouv, pour les "gros morceaux" (node, postgres, hasura, next... ?)

**Comment by revolunet** [comment]
je suis d'accord que les migrations des mineures et + doivent s'accompagner dune lecture du changelog :)

**Comment by douglasduteil** [comment]
:wave: 

Beaucoup de chose a discuter.

Perso ma vision en gros c'est que renovate est outil de maintenance des dépendances qui devrait être configuré pour permettre d'avoir du code "evergreen".

<br>

Le code "evergreen" :
- garantie d'être aligné avec la doc a dispo
- garantie le moins de vulnérabilité sur le code des dépendances
- garantie moins de bug due aux dépendances qu'on utilise
- garantie de pouvoir toujours bénéficier des dernières features 

<br>


Pour moi le flow de base serait 
- 1 PR atomique quelque soit le type de mise a jour (patch, mineur, majeur)
  - pour garantir le maximum de flexibilité vis a vis de bump no-compatible avec notre code
  - pour nous protéger des erreurs humaines (patch foiré, packages vide, etc..)  
- lancement de tests défensifs contre les libs utilisées
  - **Les tests sont le nerf de la guerre pour moi**
  - sans tests d’intégration entre notre code et les dépendances, on ne peut pas merge sans tester manuellement (une ou what-mille prs du bot) et on peut pas automerge car on ne sait pas si la ou les PRs cassent l'app.
- automerge all the :heavy_check_mark: prs
  - l'automerge permet de ne pas à avoir à se soucier de 99% des PRs qui sont compatible avec notre code.
  - la plupart des majs sur un mois sont des patchs ou des minors. Notre code est, sur le semver, souvent compatible et je ne vois pas pourquoi on attendrait d'appliquer un patch qui ne casse rien.
  - :heavy_check_mark: est a notre charge.
    c'est la réponse de nos tests d’intégration ou/et e2e qui nous valide que le changement n'affecte pas plus qu'avant notre app que les cases que nous avons testé.

<br>

Je comprends votre fatigue au quotidien. Sans tests d'intégrations, pas d'automerge donc une pille de PR à tester et à merger chaque jour. Il vous faut alors changer la config renovate pour éviter le spammage ce qui peut être laborieux...

<br>

On peut effectivement ce dire que les équipes qui n'ont pas une couverture fonctionnelle suffisante doivent changer leur config en mode maj hebdomadaire des dépendances.

**Comment by lionelB** [comment]
> 1 PR atomique quelque soit le type de mise a jour (patch, mineur, majeur)
pour garantir le maximum de flexibilité vis a vis de bump no-compatible avec notre code
pour nous protéger des erreurs humaines (patch foiré, packages vide, etc..)

a 30min de build, vu la fréquence, on va saturer le build et le faire tourner la nuit ne résoud pas le problème, puisqu'on se retrouve le matin a relancer les PR qui ont faillé :(

**Comment by douglasduteil** [comment]
> a 30min de build, vu la fréquence, on va saturer le build et le faire tourner la nuit ne résoud pas le problème, puisqu'on se retrouve le matin a relancer les PR qui ont faillé :(

Il faut effectivement qu'on passe de 30 a 10min de build sur cdtn
et qu'on trouve une solution pour ne pas a avoir a retry a la main

**Comment by revolunet** [comment]
Hello,

suite à vos différents retours, on a publié un preset "light" et une mini doc ici : https://socialgouv.github.io/support/#/faq?id=utilisation-de-renovate

on itère là-dessus ! merci de votre aide 💙
