### ISSUE TITLE
GH organisation secrets

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/support#28]
Utiliser les secrets d'orga  pour NPM_TOKEN, GIT_AUTHOR_EMAIL, GIT_AUTHOR_NAME ?

https://github.com/organizations/SocialGouv/settings/secrets

**Comment by douglasduteil** [comment]
![image](https://user-images.githubusercontent.com/730511/82256896-6a216780-9957-11ea-8d35-878ea875dbc6.png)

Done

**Comment by douglasduteil** [comment]
tested here https://github.com/SocialGouv/linters/blob/master/.github/workflows/ci.yml#L58-L76

**Comment by revolunet** [comment]
thanks !
