### ISSUE TITLE
[sécu]: limiter les accès au SOCIALGROOVYBOT_BOTO_PAT

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/support#290]
Principalement utilisé par semantic-release a priori

**Comment by Matmut7** [comment]
Atténuation court terme : enlever les droits **orga** au bot en lui laissant seulement les droits admin de tous les **repos**.

Solutions long terme :
- ne pas protéger les branches
  - permet à `GITHUB_TOKEN` de push normalement
- webhook qui écoute et release de l'extérieur des repos
  - aucun secret nécessaire dans les repos
- un bot par projet avec son PAT sur tous les repos du projet
- une deploy key par projet
  - permet à Kontinuous de de `git push` en ssh

**Comment by revolunet** [comment]
Solution court terme :
 - downgrade du user `SocialGroovyBot` en member classique
 - ajouter à une team `SocialGroovyBot` dédiée qui a les droits d'admins sur les 49 repos utilisant le token

test OK sur les repos www et standup

**Comment by Matmut7** [comment]
A priori il est possible de faire tourner semantic release avec les privilèges d'une deploy key (test : https://github.com/SocialGouv/actions-runner/commit/6f790d142b4100025d0168b684a93dbde52b2212)

**Comment by Matmut7** [comment]
Décision d'utiliser la deploy key de chaque repo pour release sur master. Il sera donc impossible de garder l'interdiction de bypass admin.

Proposition sur la méthode de release à standardiser :
- proposer une action `semantic-release`
- par défaut : exécution automatique sur master à chaque merge (non push pour éviter le bug de release en boucle)
- possibilité d'exécuter plutôt manuellement pour avoir moins de releases

**Comment by Matmut7** [comment]
Début des migrations une fois que les deploy keys seront placées sur tous les repos.

**Comment by revolunet** [comment]
je sais plus où on en est là-dessus ?

**Comment by matmut7** [comment]
Lié à #300

**Comment by revolunet** [comment]
a priori on ne sait pas limiter la diffusion sur les repos car utilisé notamment par semantic-release
