### ISSUE TITLE
Suivi technique des produits

### ISSUE THREAD

**Issue by matmut7** [SocialGouv/support#310]
Review en équipe d'un produit toutes les semaines selon une checklist de points d'attention (maintenabilité, respect des standards, etc.).

https://docs.google.com/spreadsheets/d/1rk1fWiAoAAjJu1qrGMC2_SxCmFuq6A9Vk9aRBCADCgA/edit#gid=1381074018

**Comment by Matmut7** [comment]
Compléter la checklist et trouver un créneau (régulier ou non).
