### ISSUE TITLE
Organiser des présentations

### ISSUE THREAD

**Issue by matmut7** [SocialGouv/support#311]
Présentations techniques adressées aux membres de la Fabrique par les SRE.

### Le but
Aborder des points techniques propres à la Fabrique permettra à la fois de développer la relation entre SRE et les produits, et de mieux standardiser la plateforme technique.

### Les règles
- 15, 20 minutes de présentation maximum (si la présentation est trop longue, il faut la diviser en plusieurs parties)
- utiliser le theme de la Fabrique pour faire les slides de la présentation (demander à Gary)
- avoir un slide concernant l'équipe SRE en début de chaque présentation
- donner la possibilité aux spectateurs d'effectuer les memes actions que le présentateur quand cela est possible

### Exemples de sujets
- [ ] Docker et l'env de dev local
- [x] Se connecter à un cluster k8s
- [x] Se connecter à une DB
- [x] Git et le flow git Fabrique
- [ ] Talisman (@matmut7)
- [ ] Les fonctions synchrones Node
- [ ] Hasura
- [x] Template (@maxgfr)
- [ ] Sentry
- [ ] Gestion des sealed secrets
- [ ] APM
- [x] Déployer un site statique de A à Z (nextjs, template, any...)
- [ ] Tests unitaires
- [ ] ...

### Présentations disponibles
- [Le Guide de survie de la PR](https://docs.google.com/presentation/d/1x9H2-SHsF6mXuByijX7u3gTC5CeT4nmbpI1z-NOtyUE/edit?usp=sharing)

**Comment by gary-van-woerkens** [comment]
Proposition de présentation: **Le guide de survie de la PR**
Dont le menu est visible ici:
https://hackmd.io/DgdZFZr9QGyJpHanQCDCYg

**Comment by revolunet** [comment]
- gestion des sealed-secrets
 - sentry

**Comment by achauve** [comment]
- grafana : logs et dashboards
- APM

**Comment by gary-van-woerkens** [comment]
- deployer un site statique de A à Z (nextjs, template, any...)

**Comment by Matmut7** [comment]
Todo:
- travailler sur le format typique des présentations (contenu, style, rythme, etc.)
- travailler sur quelques premières présentations concrètes
- review des présentations au sein de SRE

**Comment by revolunet** [comment]
une fois les pres validées, les publier sur le site support ?

**Comment by maxgfr** [comment]
Pour les présentations, que je ferrai : 
- [ ] Template
- [ ] Tests unitaires
