### ISSUE TITLE
Onboarding membres

### ISSUE THREAD

**Issue by matmut7** [SocialGouv/support#312]
À l'arrivée d'un membre (même sur un produit existant) un rendez-vous avec les SRE serait souhaitable afin de discuter des standards, du mode de fonctionnement ou encore des choix techniques.

Ce fonctionnement devrait être en place depuis que les SRE participent au recrutement, à confirmer.

**Comment by Matmut7** [comment]
Créer le contenu de l'onboarding technique que les SRE proposeraient aux nouveaux devs
