### ISSUE TITLE
Onboarding produits

### ISSUE THREAD

**Issue by matmut7** [SocialGouv/support#313]
Les SRE ont besoin d'être présents à la création technique des produits pour discuter les choix techniques avec les développeurs.

Fonctionnement à discuter avec les responsables produits.

**Comment by revolunet** [comment]
proposer quelques slides pour les "non-devs" ?
 - a quoi sert l'équipe SRE
 - les outils prêts à l'usage à la fabrique (template, matomo, sentry...)
