### ISSUE TITLE
[secu]: TIPIMAIL : restreindre l'accès des tokens aux IPs de nos clusters

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/support#321]
Igor : 

> Pour limiter les impacts d'une autre publication accidentelle de crédential tipimail et éviter les risques de phishing, je vous propose de mettre en place sur toutes (inventaire à valider) les clés des restrictions d'IP pour limiter les accès aux services tipimail aux IPs des clusters PROD, DEV, Tools.

 - Cette solution va: 
   - Empêcher l'envoi de messages en tant que l'identité du compte depuis internet
   - Limiter l' envoi des e-mails depuis nos clusters
 - Cette solution ne va pas:
   - Empêcher à celui qui possède les identifiants de récupérer les informations présentes dans tipimail (adresse, e-mail , expéditeur, destinataire, objet du message)

Comment faire:

 - Editer les clès SMTP existantes
 - Cocher l'option Autoriser des adresses IP à utiliser la clé.
 - Ajouter les IPs prod 20.74.14.77 20.74.10.146, dev 51.103.10.142 20.74.14.116 , tools 20.74.70.130 51.11.229.162

**Comment by revolunet** [comment]
en cours par @igorrenquin

**Comment by igorrenquin** [comment]
https://gitlab.fabrique.social.gouv.fr/infra/documentation/-/issues/967
