### ISSUE TITLE
Mettre au point des recommandations pour le chiffrement

### ISSUE THREAD

**Issue by matmut7** [SocialGouv/support#326]
Pour l'exemple de Domifa qui chiffre les fichiers avec un systèmre fait maison peu standard.

À voir avec François.

**Comment by revolunet** [comment]
- [ ] chiffrement de fichiers côté backend
 - [ ] chiffrement de colonnes dans une DB
 - [ ] chiffrement e2e

**Comment by revolunet** [comment]
https://socialgouv.github.io/support/docs/standards/securite#chiffrer-des-fichiers
