### ISSUE TITLE
[cdtn-admin]: adjust dev resources requests/limits

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/support#331]
Ajuster les requests/limits en dev; actuellement : ~3cpu

**Comment by maxgfr** [comment]
J'avoue qu'il faut que je me plonge dessus comme pour cdtn.

Le service est utilisé que en interne donc on a besoin que du minimum possible

**Comment by revolunet** [comment]
(c'est surtout en dev pour l'instant)
