### ISSUE TITLE
Infra Startup

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/support#337]
# Problème

Avec le temps le module terraform de création des ressources startups ne fonctionne plus correctement.  
Les difficultés suivantes ont été identifiés:
- Difficultés de mise a jours des ressources via ce module
- Configuration compliquée
- Utilisation / mise à jour d'Atlantis
- Suivi des versions de Terraform
- Que fait le module

# Démarche de résolution
- [x] Revoir et compléter les specs du module rancher-config-setup
- [ ] Liste des specs à conserver ou a implémenter
- [ ] Choix de la solution pour implémenter
- [ ] On code comme des gorets

# DOD
- ne plus avoir à remplir de fichiers HCL
- faciliter la création d'une SE et ses ressources
- un langage de description: YAML (mode RP rules)

**Comment by revolunet** [comment]
Bug à la création de la SE:
 - ordre des commandes. namespace-ci doit être créé :
     - apres la création du projet rancher
     - avant le provisionning des secrets harbor dans *-ci

https://gitlab.fabrique.social.gouv.fr/infra/infra-startup/-/merge_requests/171

**Comment by revolunet** [comment]
le NS de prod n'est plus crée ? a vérifier

**Comment by revolunet** [comment]
https://hackmd.io/@5eaaFGMWTfeaTaAsl2Q3OQ/rJy9N4rOj/edit

**Comment by igorrenquin** [comment]
@igorrenquin planifier une réunion pour init une SE ensemble et écrire le dérouler.

**Comment by revolunet** [comment]
test fait hier : ajout de recosante

 - il faut ajouter les ressources de DB avant startup-bootstrap sinon ca crash
 - erreur au 1er lancement de startup-bootstrap, il faut relancer (pb de ns-ci)
