### ISSUE TITLE
Optimisation de la CI

### ISSUE THREAD

**Issue by gary-van-woerkens** [SocialGouv/support#340]
- Problème :
    - ne pas déployer systématiquement des environnements de review lorsque ca n'est pas necessaire

- TODO:

- [ ] Optimisation de l'usage des ressources par les env de review, plusieurs actions:
  - [x] config du cluster kubernetes (OPS)
    - [x] augmenter le nombre de pods par noeud
    - [ ] réduire la taille des noeuds
  - [x] réduction des env de review (SRE)
    - [x] études à réaliser:
      - [x] sondage auprès des dev
      - [x] analyse du traffic sur les env de review
    - [x] actions on workflows (l'une ou l'autre)
      - (convention on demand review env, eg: branch naming dev/*)
      - [x] déclenchement manuel de l'action dans github

**Comment by revolunet** [comment]
grafana : [etude des requetes sur cluster dev](https://grafana.fabrique.social.gouv.fr/d/AAkUEN54k/dev-ingress-hits?from=now-1h&to=now)

**Comment by devthejo** [comment]
sondage équipe cdtn:
eux utilisent beaucoup les env de review, une convention de nommage des branches leur conviendrais mieux

peut être que le bon compromis serait d'avoir les 2: feat/* fix/* créént un env de review automatiquement, les autres déclenchent un workflow qu'il faut valider manuellement

**Comment by igorrenquin** [comment]
Pour la réduction de la taille des noeuds on verra avec le retour d'expérience suite à la mise à jour du ma pod.
