### ISSUE TITLE
Gestion automatique du bastion ?

### ISSUE THREAD

**Issue by gary-van-woerkens** [SocialGouv/support#343]
Autoriser automatiquement les comptes GitHub au bastion

Ex: https://github.com/revolunet.keys

## Problème

Difficulté pour maintenir la base des clés SSH autorisées à se connecter

## Dod

Un dev ajouté à une team admin a automatiquement accès au bastion

**Comment by igorrenquin** [comment]
- [ ] Tester l'accès via un client PGAdmin via teleport
