### ISSUE TITLE
Postgres Operator

### ISSUE THREAD

**Issue by igorrenquin** [SocialGouv/support#352]
On passe à la phase de test fonctionnel sur l'opérateur postgres

- Suite à la présentation des operateur postgres sur kubernetes. Stackgres a été sélectionné pour passer à la phase de test fonctionnel.

- [x] Création de l'application stackgres
- [x] 1er déploiement de l'opértator à 4 :hand: sur les outils SRE
- [x] Bascule de Secretariat vers `CNPG` ou `Stackgres` -> lundi 15h - 18h
- [ ] Tests à réaliser
  - [x] backups et les restore CNPG réguliers
  - [ ] backups et les restore CNPG `just in time`
- [ ] Conclusion du test
- [ ] Définir la stratégie par défaut pour backups de prod si on utilise CNPG

**Comment by igorrenquin** [comment]
- tester les backups régulier
- tester les backups `just in time`
- tester le ssl en cas de changement d'instance (actuellement constaté reset de connexion)

**Comment by revolunet** [comment]
Etudier le cas de la gestion des backups sur OVH

**Comment by igorrenquin** [comment]
Question: @octomir 
problème sur la tâche de recovery du `just in time` 
 comprendre comment `barman` fonctionne pour restorer un WAL voir s'il y a des élements de configuration à modifier.

pour l'instant c'est limité à un peu après le backup.

**Comment by revolunet** [comment]
Upgrader l'opérateur à la derniere version ?

**Comment by octomir** [comment]
@matmut7  ou autre : nous avons fait l'upgrade sur OVH, est-il possible de faire une non reg sur ovh avant de généraliser

**Comment by matmut7** [comment]
Yes on s'occupe de tester ça, merci !

**Comment by revolunet** [comment]
faire fonctionner le backup/restore avec OVH

**Comment by revolunet** [comment]
Backups OK, restore à tester

attention a bien préciser la region du storage pour OVH/S3
