### ISSUE TITLE
[question]: QUID nécessité d'utiliser le DNS azure pour le dev ?

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/support#355]
Pourquoi a-t-on besoin de déclarer toutes les entrées DNS de dev sur azure alors qu'on a un wildcard ?

L'IP par défaut d'un host en `*.dev.fabrique` est 51.138.205.91. si ca pouvait etre 51.103.10.142 ca nous éviterait des soucis de cache DNS

**Comment by revolunet** [comment]
fix: correction de l'IP par défaut sur dev en 51.103.10.142

**Comment by igorrenquin** [comment]
Mise à jour de l'IP destination pour point vers l'IP du cluster DEV

**Comment by revolunet** [comment]
côté OPS : voir si nécessaire de garder external dns pour les `*.dev.fabrique`
