### ISSUE TITLE
[sentry] : test  v23.1.1

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/support#357]
https://sentry.test.lafabriquenumerique.cloud-ed.fr/auth/login/sentry/

**Comment by revolunet** [comment]
test ici : https://github.com/SocialGouv/template/pull/148

**Comment by revolunet** [comment]
@achauve tu vois des applis à tester ?

@igorrenquin on previent nos amis de la DNUM ?

**Comment by igorrenquin** [comment]
> @achauve tu vois des applis à tester ?
> 
> @igorrenquin on previent nos amis de la DNUM ?

Yes DNUM
- PSN
  - 1j1S
  -   dematsocial
- SCN ARS
  - Helios
  
  Il y a peut-être aussi du ménage à faire:
- Project:
  - C ?
  - CDTN-contributions ?
  - demande-rc ?
  - dematsocial-back ?
  - dematsocial-front ?
  - doc-rn ?
  -  eaps ?
  - internal ? 
  - Medle
  - ONVS
  - Work-in-France
- Teams
  - eaps ?
  - medle
  - onvs
  - textstyle
  - transition-collectives

**Comment by revolunet** [comment]
mail envoyé avec deadline au 15/03
