### ISSUE TITLE
[recosante]: import projet sur infra startup

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/support#370]
- Rapatrier le hosting de recosante sur plateforme fabrique
 - Rapatrier le NDD et les emails

https://pad.incubateur.net/U1sqdDIcS2ukXN1ZI-T2jw?both

**Comment by revolunet** [comment]
Reste : 
 - gestion du volume "FS"  (ftp?) sur indice_pollution
 - rebrancher le `GATSBY_API_BASE_URL`
 - quid échanges send in blue

**Comment by revolunet** [comment]
retours à faire à l'équipe : 
 - mieux documenter les vars d'env
 - fixer les versions dans les requirements
 - fournir des Dockerfile fonctionnels

**Comment by achauve** [comment]
- ftp : Azure ou hébergement / monté dans indice_pollution / test
- pre-dump équivalent alembic pour accélérer le démarrage du dev
- rapatrier dernière version front avec accessibilité
- tester dump SQL de prod en preprod
- passer le frontend de dev sur l'api de dev et checker les données

**Comment by achauve** [comment]
remplacer partout les recosante.beta.gouv.fr (notamment dans le front)
