### ISSUE TITLE
Environnement de dev persistant

### ISSUE THREAD

**Issue by achauve** [SocialGouv/support#373]
Actions pour avoir des env de dev persistants : 

- cleaning des images harbor
- cleaning des images ghcr
- build des images dans workflows
- build ET utilisation des images dans kontinuous
- deactivate

Prendre en charge une branche du type `persist-*`. Convention à adapter en traitant le ticket.

**Comment by revolunet** [comment]
c'est bien implémenté côté harbor : https://gitlab.fabrique.social.gouv.fr/infra/terraform-modules/resources/startup-bootstrap/-/blob/main/harbor.tf
