### ISSUE TITLE
[Monitoring] exporter dans prom les rapport des scan de vulnérabilités réalisés

### ISSUE THREAD

**Issue by igorrenquin** [SocialGouv/support#377]
# Contexte

Les images  des produits sont scannés pour identifier les vulnérabilités.
- La CI intégre un scan de vulnérabilité (à confirmer)
- Dashlord intégre un scan de vulnérabilité (Trivy)
- Harbor pour les images s'y trouvant scanne les vulnarabilités (Trivy). 

Les scans sont dispersés et sont rarement consultés par les équipes et cela à pour effet de ne pas ou rarement intégrer à la vie du produit la mise à jour des couches techniques.

Pour réduire ce risque de sécurité il faudrait mettre à disposition dans un endroit unique un rapport des vulnérabilités sur les images.

# DOD
- Exporter les informations de scan dans prometheus pour être consommé dans des dashboards mis à disposition des équipes produits
  - visualiser les informations suivantes:
    - projet
    - image name
    - image tag/ version
    - Nom vulnérabilité
    - Criticité de la vulnérabilité
    - Vulnérabilité fixable

**Comment by revolunet** [comment]
a priori cet outil fait le job ; https://aquasecurity.github.io/trivy-operator/v0.13.1/

**Comment by revolunet** [comment]
dispo dans le dashboard grafana/trivy
