### ISSUE TITLE
[docker]: créer un tag `latest` sur les builds de prod

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/support#380]
S'assurer qu'on enregistre bien un tag `latest`lorsqu'on push une nouvelle image de prod

ceci permet à dashlord de faire le scan sans avoir besoin de connaitre la derniere version

**Comment by revolunet** [comment]
côté kontinuous a priori: 
 - https://github.com/SocialGouv/workflows/blob/master/actions/workflows-build-images/action.yaml
 - https://github.com/SocialGouv/workflows/blob/master/actions/build-image/action.yaml
 - https://github.com/SocialGouv/kontinuous/blob/master/plugins/contrib/jobs/build/use.yaml

sur mano par exemple ca a l'air OK, le latest existe bien

**Comment by revolunet** [comment]
**archifiltre-statistic**
utilise [SocialGouv/actions/autodevops-helm](https://github.com/SocialGouv/actions/blob/master/autodevops-helm/action.yml)
 - prod: ghcr.io/socialgouv/archifiltre/archifiltre-statistics:1.19.28
 - latest ✅ : ghcr.io/socialgouv/archifiltre/archifiltre-statistics:latest

**archifiltre-site**
utilise [ SocialGouv/actions/autodevops-build-register](https://github.com/SocialGouv/actions/blob/master/autodevops-build-register/action.yml)
  - prod: ghcr.io/socialgouv/archifiltre/archifiltre-site:2.0.6
  - latest ❌ : ghcr.io/socialgouv/archifiltre/archifiltre-site:latest

**archifiltre-site-v2**
utilise [use-ks-gh-production.yaml](https://github.com/SocialGouv/workflows/blob/master/.github/workflows/use-ks-gh-production.yaml)
 - prod: harbor.fabrique.social.gouv.fr/archifiltre/archifiltre-site-v2/app:v1.12.0
 - latest ❌ : harbor.fabrique.social.gouv.fr/archifiltre/archifiltre-site-v2/app:latest

**cdtn-api**
utilise [ SocialGouv/actions/autodevops-build-register](https://github.com/SocialGouv/actions/blob/master/autodevops-build-register/action.yml)
 - prod: ghcr.io/socialgouv/cdtn/code-du-travail-api:4.91.1
 - latest ❌ : ghcr.io/socialgouv/cdtn/code-du-travail-api:latest

**cdtn-front**
utilise [ SocialGouv/actions/autodevops-build-register](https://github.com/SocialGouv/actions/blob/master/autodevops-build-register/action.yml)
  - prod: ghcr.io/socialgouv/cdtn/code-du-travail-frontend:4.91.1
  - latest ❌ : ghcr.io/socialgouv/cdtn/code-du-travail-frontend:latest

**domifa-backend**
utilise [use-ks-gh-production.yaml](https://github.com/SocialGouv/workflows/blob/master/.github/workflows/use-ks-gh-production.yaml)
 - prod: harbor.fabrique.social.gouv.fr/domifa/domifa/backend:v2.120.1
 - latest ❌ : harbor.fabrique.social.gouv.fr/domifa/domifa/backend:latest

**template-app**
utilise [use-ks-gh-production.yaml](https://github.com/SocialGouv/workflows/blob/master/.github/workflows/use-ks-gh-production.yaml)
 - prod: harbor.fabrique.social.gouv.fr/fabrique/template/app:v1.15.0
 - latest  ❌ : harbor.fabrique.social.gouv.fr/fabrique/template/app:latest

**Comment by revolunet** [comment]
sur mda, qui utilise `use-ks-gh`, pas de tag latest sur harbor

**Comment by devthejo** [comment]
https://github.com/SocialGouv/workflows/pull/9

**Comment by devthejo** [comment]
https://github.com/SocialGouv/kontinuous/pull/253

**Comment by revolunet** [comment]
Thanks! je rajoute https://github.com/SocialGouv/actions/pull/179
