### ISSUE TITLE
[e2esdk]: évaluer le SDK

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/support#398]
Mettre en oeuvre le SDK pour évaluer :

 - [ ] coût d'implémentation/complexité dans une app
 - [ ] aspects UX (login, restore...)
 - [ ] backups/risques
 - [ ] performances (fichiers)

idéalement on travaille sur un use-case réel ou réutilisable

On pourrait par ex tester sur une branche dédiée de EDS ?

**Comment by matmut7** [comment]
Tout à fait !

Est-ce qu'avant on essaie de se faire la main sur un projet plus simple comme template ou les formulaires E2EE ?

**Comment by revolunet** [comment]
on se prend une journée pour tenter d'ajouter le use-case des formulaires sur template ?

 - des users anonymes peuvent poster des données/fichiers (formulaire)
 - des users authentifiés peuvent afficher ces données et se les partager

**Comment by revolunet** [comment]
Prérequis :
 - serveur de test e2esdk
 - local running template@hasura dev environment

Etapes possibles :
 - Ajouter un formulaire dans le front
 - Créer une table pour recevoir les résultats côté db (hasura)
 - Ajouter e2esdk dans le submit du form + submit hasura
 - Vérifier que ça record bien en db
 - Logguer/registre e2esdk auto au login des admins
 - Afficher la liste des résultats déchiffrée
 - Ajouter un exemple avec upload fichiers

**Comment by revolunet** [comment]
Création par l'admin du form : https://github.com/SocialGouv/e2esdk/blob/beta/examples/fullstack/contact-forms/src/pages/app/contact-forms/new.tsx

```
await client.sodium.ready
const { nameFingerprint, publicKey } = await client.createKey(
  `forms:answers:contact-form`,
  'sealedBox'
)
// --> nameFingerprint, publicKey needed to post the form data
```

then on client :

```
const submissionBucketId = "xxx" // nameFingerprint from form creation
const state = await initializeEncryptedFormLocalState(submissionBucketId)
const formData = new FormData()
const { metadata, encrypted } = encryptFormData(formValues, state)

const variables: SubmitContactFormVariables = {
  submissionBucketId,
  sealedSecret: metadata.sealedSecret,
  signature: metadata.signature,
  publicKey: metadata.publicKey,
  ...encrypted,
}
const res = await request<InsertResponseData>(
  'http://localhost:4002/v1/graphql', // todo: Use env
  SUBMIT_CONTACT_FORM_MUTATION,
  variables
)

```

**Comment by revolunet** [comment]
Next steps :
 - decrypt and zod validate the submitted data ([ex](https://github.com/SocialGouv/e2esdk/blob/beta/examples/fullstack/contact-forms/src/lib/submissions.ts#L192))
 - add example file encrypt/upload/download/decrypt

**Comment by matmut7** [comment]
Déchiffrement implémenté ✅ 
https://github.com/SocialGouv/template/pull/154

**Comment by revolunet** [comment]
- Questions
     - comment share avec un utilisateur qui n'existe pas encore dans l'appli et/ou e2esdk
     - comment déployer mon appli avec des buckets déjà opérationnels ?
     - comment retrouver mon login/clés depuis un password (revovery)
 - Reste à faire
     - PR pour découpler le url hash de la public key du form
     - PR pour ajouter le component DevTools
     - ajouter exemple de file encrypt/upload/download/decrypt
     - envoi invitation de partage
     - Documentation:
       - usage guide pours les devs
       - améliorer la TSDoc
     - voir si besoin d'ajouter des APIs plus haut niveau
