### ISSUE TITLE
Kubeconfig créés via INFRA-STARTUP

### ISSUE THREAD

**Issue by gary-van-woerkens** [SocialGouv/support#401]
Lors de la création de la SE `Nata`, le premier apply d'atlantis a créé des Kubeconfig vides (dans les secrets Github et dans les secrets sur Kube).

Une fois les mauvais Kubeconfig supprimés et l'atlantis relancé, tout fonctionne correctement.

**Comment by igorrenquin** [comment]
Idée de résolution.

Implémenter rrenovate sur infra-startup qui vérifierai les tags de version sur infra/moduules-terraform

**Comment by revolunet** [comment]
tester sur une nouvelle SE:
 - RBAC k9s 
 - kubeconfig OK sur GitHub

**Comment by octomir** [comment]
In review FIX :
[v0.1.4](https://gitlab.fabrique.social.gouv.fr/infra/terraform-modules/resources/startup-bootstrap/-/tags/v0.1.4)
a tester sur une nouvelle SE:
RBAC k9s
kubeconfig OK sur GitHub
