### ISSUE TITLE
harbor : check rules deletion

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/support#413]
Où sont dans le code infra les règles harbor ?

Pour verifier qu'on est à jour

https://gitlab.fabrique.social.gouv.fr/infra/tools/harbor

https://github.com/SocialGouv/support/issues/373

**Comment by octomir** [comment]
Bloc de lignes 41-49

[Harbor suppression de tags : fichier harbor.tf](https://gitlab.fabrique.social.gouv.fr/infra/terraform-modules/resources/startup-bootstrap/-/blob/main/harbor.tf)

**Comment by revolunet** [comment]
nice merci
