### ISSUE TITLE
IaC: perte d'un réglage sur un repo Github

### ISSUE THREAD

**Issue by matmut7** [SocialGouv/support#415]
Certains projets utilisent des **environnements protégés**, notamment pour choisir manuellement quand déployer en production :

![Image](https://github.com/SocialGouv/support/assets/38255502/6927382e-191f-489c-a6f7-46e98f2025a4)

Sur le repo `secretariat`, ce réglage était utilisé mais a été **supprimé via l'API** inexplicablement :

![Image](https://github.com/SocialGouv/support/assets/38255502/1a016dc5-5952-40c4-9ce3-534de7c23b25)

**Comment by revolunet** [comment]
je pense qu'on peut voir un ex ici : https://gitlab.fabrique.social.gouv.fr/infra/infra-startup/-/merge_requests/232

**Comment by octomir** [comment]
Intégration requise review pour l'environnement de prod dans le coté IaC
dans le cas ou j'initie un code TF avec la partie required review la config est bien prise en compte

**Comment by octomir** [comment]
Release :
[v0.1.9](https://gitlab.fabrique.social.gouv.fr/infra/terraform-modules/resources/startup-bootstrap/-/tags/v0.1.9)

**Comment by revolunet** [comment]
Je ne sais pas si c'est normal; Je te tente de run la 0.1.12 sur 1000jours.

Sur GitHub dans le repo 1000jours j'ai bien un environnement production de configuré avec des reviewers

![Image](https://github.com/SocialGouv/support/assets/124937/c46e76b4-95b4-434f-9f1d-0f44480fcd72)

Dans le atlantis plan ca me dit : 

```
  # github_repository_environment.startup_repository_environment["1000jours"] will be created
  + resource "github_repository_environment" "startup_repository_environment" {
      + environment = "production"
      + id          = (known after apply)
      + repository  = "1000jours"

      + reviewers {}
    }
```

**Comment by revolunet** [comment]
Je confirme que ca a détruit puis recrée les envs de prod sur tous les repos jours 1000jours, et donc les reviewers affectés à cet environnement

![Image](https://github.com/SocialGouv/support/assets/124937/ce344df2-3b7d-4894-8628-47aec3fe2e34)

**Comment by revolunet** [comment]
pour les envs de review, s'ils sont créés par TF il faudrait ajouter l'équipe SRE en reviewers en plus de l'équipe "Admins Xxx"

**Comment by octomir** [comment]
en effet le il y a bien une issue je le repasse en doing

**Comment by revolunet** [comment]
https://gitlab.fabrique.social.gouv.fr/infra/infra-startup/-/merge_requests/254

**Comment by octomir** [comment]
Apres Investigation, vérification et échange avec @revolunet 
le cas identifié qui génère ce comportement serait le cas ou l'environnement "production" aurait été généré hors IaC donc pas présent dans le TFState l'apply du IaC régénère l'environnement de production comme s'il était crée sans vérifier qu'il existe déja et sans crée d'erreur de type 409 conflit (ce qui est souvent observé)
Si le message 
`github_repository_environment.startup_repository_environment["xxxxxx"] will be created` -> ping @OPS pour investigation

**Comment by revolunet** [comment]
apres avoir updaté [infra-startup sur tumeplay](https://gitlab.fabrique.social.gouv.fr/infra/infra-startup/-/merge_requests/265) ce matin, je vois ca : 


![Image](https://github.com/SocialGouv/support/assets/124937/4353b310-f729-41e0-a296-7ea86ae75468)
