### ISSUE TITLE
CNPG OVH + grafana dashboard

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/support#426]
Pouvoir consulter les metriques des CNPG OVH sur les dashboard CNPG grafana

**Comment by octomir** [comment]
il semblerait qu'il y a une régression sur la helm qui déploie sur ovh 
@revolunet  quelle est la valeur du enablePodMonitor depuis la chart ?? 
je vois que dans le cluster déployé nous avons "enablePodMonitor: false"

**Comment by revolunet** [comment]
ok ceci explique cela merci ! je retente avec `true`

**Comment by revolunet** [comment]
nickel a ca l'air de marcher 🙏 

![](https://media.giphy.com/media/B37cYPCruqwwg/giphy.gif)
