### ISSUE TITLE
CNPG OVH + storages backup

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/support#428]
En prod, avoir des credentials par SE pour pouvoir créer/pousser des backups CNPG

Limiter les droits avec les policy S3
 - un bucket pré-créé, ex : `backups-cnpg-prod-cdtn`
 - un secret dédié dans le NS : `ci-cdtn`
 - la policy S3 doit limiter les droits au bucket en question

Intégrer dans startup-bootstrap

**Comment by revolunet** [comment]
recetter le bucket + secret et policy s3

**Comment by achauve** [comment]
- Pas prioritaire tant qu'on passe pas sur CNPG
- les backups marchent bien en n'oubliant pas le paramètre `region` dans le chart du cluster CNPG qu'on peut utiliser via kontinuous (cf le helm chart cnpg cluster sur https://socialgouv.github.io/helm-charts/).
- Le jour venu on aura besoin d'un bucket et d'un user par startup.

**Comment by igorrenquin** [comment]
Ajouter l'execution d'un Dump sur l'instance de prod.
A discuter: 
- rétention
- nb d'exécution par /jour
- position de la sauvegarde
- génération du cronjob pour l'instance

**Comment by igorrenquin** [comment]
- Tester le déploiement d'un stockage S3  en IaC pour intégration dans le helm chart

mi aout au retour d'Adrien

**Comment by igorrenquin** [comment]
- Tester de déposer des backups PGDump dans ce storage

**Comment by igorrenquin** [comment]
### SRE
- Mise en place d'un job via la CI pour effectuer les backups de DB
- Ajout du cron job dans le Helm chart CNPG cluster

**Comment by matmut7** [comment]
Partir de [ces scripts](https://gitlab.fabrique.social.gouv.fr/infra/terraform-modules/ovh/postgresql/-/tree/main/scripts)

**Comment by revolunet** [comment]
fix sur le module OVH : https://gitlab.fabrique.social.gouv.fr/infra/terraform-modules/ovh/storage-object/-/merge_requests/4

**Comment by revolunet** [comment]
liens vers scripts de rotate : https://gitlab.fabrique.social.gouv.fr/infra/terraform-modules/postgresql-managed-db/-/tree/master/super/scripts

**Comment by igorrenquin** [comment]
RAF:  Ajouter des dumps SQL sur la base des jobs identiques aux jobs de sauvegarde pg AZ

- Les dumps sont stockés sur le même S3 que les sauvegardes bareman
- mettre en place la rétention des sauvegardes
