### ISSUE TITLE
Test pulumi

### ISSUE THREAD

**Issue by achauve** [SocialGouv/support#431]
Scope test pulumi : 

- positionner des variables sur github for team github for repo in team via list yaml des teams (attention repo dans 2 teams)  -> `KUBECONFIG_OVH`
- créer team et team admin github
- télécharger KUBECONFIG dev et prod depuis le cluster (ci-project)
- créer des buckets OVH pour backups CNPG (un bucket et un user par startup) et positionner le secret dans ci-project
- lire la doc de OVH storages
- bilbio test rancher local pour création compte bot + créer project rancher

TERRAFORM : 
- désactiver module github sur OVH et à moyen terme sur Azure aussi

LONG TERME : 
- gérer overrides team github vs projet rancher vs namespace ci
- créer compte bot sur rancher et mettre les kubeconfig sur le cluster

**Comment by maxgfr** [comment]
+1
