### ISSUE TITLE
Page maintenance + DSFR

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/support#461]
Remplacer la page de maintenance générique par celle avec le DSFR : https://github.com/SocialGouv/maintenance

preview : https://socialgouv.github.io/maintenance/

![](https://user-images.githubusercontent.com/124937/265019997-70811687-3879-457a-b869-2039c5afbcd5.png)

**Comment by igorrenquin** [comment]
OPS : On met à jour le backend nginx pour y déployer cette nouvelle page.

**Comment by revolunet** [comment]
Il faudrait retirer `[Nom du site]` de la page
