### ISSUE TITLE
CNPG en PROD Azure

### ISSUE THREAD

**Issue by octomir** [SocialGouv/support#466]
Dans le cadre de l’intégration et généralisation de l'utilisation de CNPG dans les startups, nous effectuons le déploiement de CNPG dans un environnement de production

**Comment by octomir** [comment]
Est-il possible d'avoir une liste des start-up cibles ?

**Comment by revolunet** [comment]
Si ça fonctionne comme attendu, elles sont toutes concernées

**Comment by igorrenquin** [comment]
Pour limiter le risque d'avoir des pods Kill 'evicted'
- [ ] mettre en place des `requests` `limits`
- [ ] ajouter des priority class sur les pod cnpg
