### ISSUE TITLE
Correction des API kubernetes deprecated

### ISSUE THREAD

**Issue by igorrenquin** [SocialGouv/support#472]
# Contexte

Dans l'objectif préparer la monter de version des clusters Kubernetes localisé sur Azure. Il faudrait corriger les API kubernetes `deprecated` ou `remove` à partir des version 1.25.

## Environnement DEV

Kube version | KIND | NAMESPACE | NAME | API VERSION | REPLACE WITH
-- | -- | -- | -- | -- | --
1.26 | HorizontalPodAutoscaler | 1000jours-preprod | strapi | autoscaling/v2beta2 | autoscaling/v2 (1.23.0)
1.26 | HorizontalPodAutoscaler | 1000jours-preprod | strapi-cache | autoscaling/v2beta2 | autoscaling/v2 (1.23.0)

## Environnement PROD

Kube version | KIND | NAMESPACE | NAME | API VERSION | REPLACE WITH
-- | -- | -- | -- | -- | --
1.22 | Ingress | fabrique | www-redirect | extensions/v1beta1 | networking.k8s.io/v1 (1.19.0)
1.25 | CronJob | covid | covid-export-tests-publics | batch/v1beta1 | batch/v1 (1.21.0)
1.25 | CronJob | infra-startups | infra-as-loop-job | batch/v1beta1 | batch/v1 (1.21.0)

# Démarche de résolution

- [x] Correction des déploiements sur le cluster de DEV
- [x] Correction des déploiements sur le cluster de PROD
- [x] Correction de la CI pour utiliser les bonnes versions d'API

**Comment by revolunet** [comment]
Ce sont des vieilles ressources qui n'etaient plus utilisées
