### ISSUE TITLE
modification falco

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/support#481]
Où modifier les alertes falco ?

Exemple, supprimer : 

 - `container.name` : hasura
 - `proc.name` : cli-ext
 - `proc.pname` : hasura-cli

**Comment by revolunet** [comment]
cf https://mattermost.fabrique.social.gouv.fr/default/pl/g67u4m38mtnwdx5n51tx4c5sia

**Comment by revolunet** [comment]
on a toujours le probleme des buildkits (+500 msg/jou)

**Comment by revolunet** [comment]
![Image](https://github.com/SocialGouv/support/assets/124937/4ee1986f-3b5a-4fb2-bb4d-4eca3eed4f74)

**Comment by revolunet** [comment]
@LucasBassoOcto où peut-on faire une MR pour proposer une règle dédiée falco ?

**Comment by igorrenquin** [comment]
@LucasBassoOcto ajouter la régle correspondante à l'allerte hasura ci-dessus
