### ISSUE TITLE
Suppression des accès Julien BOUQUILLON

### ISSUE THREAD

**Issue by igorrenquin** [SocialGouv/support#525]
Julien nous a quitté pour de nouvelles aventures. Il faut supprimer ces accès.

- [ ] github
  - [x] passage de `owner` en `member` 
  - [x] suppression de la team SRE
  - [x] suppression de l'organisation `SocialGouv`
- [X] gitlab
- [x] matomo
- [x] sentry
- [X] azure
- [X] scaleway
- [X] ovh
- [x] ES Cloud
- [ ] autre???

Attention aux impacts que pourraient avoir la suppression de son compte

**Comment by igorrenquin** [comment]
passage du compte de admin en member
sortir julien de la team SRE @igorrenquin 
suppression du compte de l'organisation github

**Comment by igorrenquin** [comment]
passage du compte de `owner` en `member` réalisé

**Comment by LucasBassoOcto** [comment]
Supression de Julien de la team SRE a effectué avant le Mardi 23 Janvier 2024

**Comment by igorrenquin** [comment]
[x] suppression du compte de julien de la team SRE

**Comment by igorrenquin** [comment]
- suppression de SocialGouv
- supression de Escloud

Ajout de adrien, matéo, gary sur tous les comptes tipi

**Comment by igorrenquin** [comment]
Done 👍
