### ISSUE TITLE
PG à supprimer sur AZ post migration

### ISSUE THREAD

**Issue by igorrenquin** [SocialGouv/support#526]
Liste des SE qui utilisent actuellement CNPG et pour lesquels on peut supprimer les instances postgreSQL Azure:

- [x] Enfants du Spectacle DEV
- [x] Enfants du Spectacle PROD
- [X] Jardin mental DEV
- [x] Jardin mental PROD 
- [x] maison de l'autisme DEV
- [x] maison de l'autisme PROD
- [x] Mano DEV
- [x] Mano PROD
- [x] 1000jours DEV
- [x] 1000jours PROD
- [x] ozensemble DEV
- [x] ozensemble PROD
- [ ] ~~recosante DEV~~ (pas présent sur Azure)
- [ ] ~~recosante PROD~~ (pas présent sur Azure)
- [X] secretariat DEV
- [X] secretariat PROD
- [ ] ~~template DEV~~  (pas présent sur Azure)
- [ ] ~~template PROD~~  (pas présent sur Azure)
- [X] Tumeplay DEV
- [X] Tumeplay PROD
- [X] MonPsySanté DEV
- [X] MonPsySanté PROD

**Comment by igorrenquin** [comment]
@gary-van-woerkens 
- est-ce-que la liste est bonne?
- peut-elle être complétée?

**Comment by gary-van-woerkens** [comment]
La liste que j'ai ajouté me semble correcte.
Elle sera a compléter au fur et à mesure de la migration, certainement.

**Comment by LucasBassoOcto** [comment]
On a encore des connections sur tumeplay dev, mda dev, ozensemble prod. Des idées ?

**Comment by igorrenquin** [comment]
Reste à supprimer le code source. Planifié pour vendredi.

**Comment by igorrenquin** [comment]
Done 👍
