### ISSUE TITLE
[Azure] suppression des applications migrées

### ISSUE THREAD

**Issue by igorrenquin** [SocialGouv/support#536]
# Contexte

Migration vers OVH des applications. Certaines applications ont migré et tournent sur OVH depuis quelques semaines.
Pour réduire les coûts et garantir une bonne hygiène sur la plateforme il faudrait identifier et supprimer toutes les ressources qui se trouveraient toujours sur les environnements Azure.

Ressources kubernetes : `pods`, `deployments`, `secrets`, `namespaces`, `job`, `cronjob`
Ressources Rancher : `projets, accès équipes
Ressources Azure : `postgresql`, `stockages`, `accès`

**Comment by matmut7** [comment]
✅ fait pour les applis migrées à ce jour

suivi [ici](https://docs.google.com/spreadsheets/d/1rk1fWiAoAAjJu1qrGMC2_SxCmFuq6A9Vk9aRBCADCgA/edit#gid=0) avec la colonne `rm azure`
