### ISSUE TITLE
nodepool dédié aux cnpg 

### ISSUE THREAD

**Issue by achauve** [SocialGouv/support#543]
Objectif : éviter les scale down sur des pods cnpg et storage. 

Solution proposée : avoir un nodepool statique qui ne scale que manuellement.

**Comment by igorrenquin** [comment]
https://github.com/cloudnative-pg/cloudnative-pg/discussions/1552

**Comment by gary-van-woerkens** [comment]
Un des changements de primary CNPG intempestifs dont on vous parlais est arrivé à ce moment-là : https://grafana.fabrique.social.gouv.fr/goto/CjvQmJ2IR?orgId=1

**Comment by igorrenquin** [comment]
@igorrenquin tableau comparatif
- tarif PG service managé OVH
- tarif CNPG

**Comment by igorrenquin** [comment]
@nicolasfournieraspicio organisation d'un point d'échange pour statuer sur les actions à cours terme pour CNPG

**Comment by igorrenquin** [comment]
Proposition de document de travail : https://www.notion.so/fabnummas/CNPG-BDD-manag-Lequel-est-le-bon-choix-pour-nous-f287b00bbc30455d8c89777c34638486?pvs=4

**Comment by igorrenquin** [comment]
Sujet plus d'actualité
