### ISSUE TITLE
Droits grafana OVH

### ISSUE THREAD

**Issue by achauve** [SocialGouv/support#545]
L'équipe SRE est actuellement admin sur le grafana OVH mais avec des droits bizarres en pratique : 

- pas possible de changer le rôle d'un user en viewer (par ex pour VAO)
- @devthejo n'a pas accès à Explore

Comment c'est sensé marcher ?

**Comment by igorrenquin** [comment]
@igorrenquin regarder les droits sur grafana ovh

**Comment by igorrenquin** [comment]
Tous les membres sont passés en editor leur donnant accès à l'explorer.
