### ISSUE TITLE
Droit Watch, List K9S

### ISSUE THREAD

**Issue by igorrenquin** [SocialGouv/support#551]

**Comment by igorrenquin** [comment]
- dev de VAO  Guillaume, etc...
- dev CJE Antoine LELONG

**Comment by LucasBassoOcto** [comment]
Fixed, le bug était localisé sur les clusters ovh

**Comment by igorrenquin** [comment]
Ajout d'un droit manquant sur les clusters OVH.
OK pour les 2 utilisateurs
