### ISSUE TITLE
[PG managé Azure] Suppression des instances non utilisées

### ISSUE THREAD

**Issue by igorrenquin** [SocialGouv/support#557]
Bonjour,
Pouvez-vous m'identifier les instances PostgreSQL manage Azure qui peuvent être supprimées?

- [x] archifiltreprodserver (delete)
- [x] carnetsdevserver
- [x] carnetsprodserver
- [x] cdtnadmindevserver (delete)
- [x] cdtnadminprodserver (delete)
- [x] coviddatadevserver (delete)
- [x] coviddataprodserver (delete)
- [x] coviddevserver (delete)
- [x] covidprodserver (delete)
- [x] domifadev
- [x] domifadevflex
- [x] domifaprod
- [x] egaprodevserver (delete)
- [x] egaproprodserver2 (waiting)
- [x] emjpmdevserver (delete)
- [x] emjpmprod (waiting)
- [x] emjpmprodserver2 (delete)
- [x] fcedevflex (delete)
- [x] fceprodsrv  (delete)
- [x] matomo-metabase (waiting)

**Comment by igorrenquin** [comment]
Information de Julien B à supprimer : 
- [ ] coviddevserver
- [ ] covidprodserver

**Comment by gary-van-woerkens** [comment]
On termine la phase de cleaning sur les clusters Azure et on fera le delete des dernieres DB a la fin.

**Comment by octomir** [comment]
en Attente de migraiton BPCO et NATA coté SRE pour suppression matomo-metabase

**Comment by igorrenquin** [comment]
arret de la matomo metabase
go pour suppression base emjpm

**Comment by igorrenquin** [comment]
Done 👍
