### ISSUE TITLE
[MDA] Suppression metabase & Matomo

### ISSUE THREAD

**Issue by igorrenquin** [SocialGouv/support#562]
La startup Maison de l'Autisme a quitté la Fabrique il y a plus d'un mois.
Nous avions laissé à disposition Metabase et matomo afin qu'il soit en capacité de reprendre des données.
Nous venons d'obtenir le GO pour supprimer ces ressources.

- [x] suppression de metabase de maison de l'autisme
- [x] suppression des accès à matomo pour les membres de MDA
- [x] suppression du site dans matomo.

**Comment by igorrenquin** [comment]
A partir du 28 mars

**Comment by gary-van-woerkens** [comment]
Ca sera fait au moment du traitement de la base commune aux SE sur Azure.... waiting.

**Comment by igorrenquin** [comment]
mettre à jour l'off boarding
