### ISSUE TITLE
cnpg RetentionPolicy

### ISSUE THREAD

**Issue by octomir** [SocialGouv/support#572]
Dans tous les déploiements des bases CNPG sur le cluster dev, il n y a aucune rétention policy sur les bases de données contrairement aux environnements de production il y a 60j 

# DOD

- [x] Définir une rétention policy pour les clusters cnpg de dev < 60j (le plus petit est le mieux)
- [ ] (Option) activer la Compression

**Comment by igorrenquin** [comment]
@igorrenquin envoi la taille des buckets S3 à Matéo

**Comment by matmut7** [comment]
- les buckets Domifa sont temporairement chargés à cause des travaux d'anonymisation
- je ne trouve pas de CNPG en dev qui n'auraient pas de retentionPolicy

**Comment by matmut7** [comment]
Pour expliciter :

- une partie du volume utilisé sur les buckets Domifa est due à des données qui viennent du chantier sur les pipelines d'anonymisation. Ce volume sera donc libéré à la fin du chantier.
- une partie de ce volume est légitimement utilisé par des clusters CNPG qui ont bien une retentionPolicy réglée. Si des clusters CNPG n'ont pas ce paramètre, alors je ne les ai pas trouvés.
- une partie de ce volume n'est pas légitime mais n'est pas due à l'absence de `retentionPolicy`. Certains répertoires de backups peuvent être orphelins, par exemple si on supprime un cluster CNPG ou qu'on change son répertoire de backups, l'ancien répertoire de backups n'est plus géré par personne et ne sera pas supprimé au bout de 60 jours. Il nous faudrait sûrement un script de nettoyage pour ce cas

Concernant mon deuxième point, j'ai vérifié les clusters CNPG de `ovh-dev` avec cette commande :

```sh
kubectl get clusters.postgresql.cnpg.io --all-namespaces -o json | jq -r '
  ["NAMESPACE", "NAME", "BACKUP", "RETENTION_POLICY"],
  (.items | sort_by(.spec.backup.retentionPolicy) | reverse | .[] | [
    .metadata.namespace,
    .metadata.name,
    (if .spec.backup == null then "null" else "set" end),
    (.spec.backup.retentionPolicy // "null")
  ])
  | @tsv
' | column -t -s $'\t'
```

qui me donne cet output où l'on peut voir que tous les CNPG ayant les backups activées ont aussi une retentionPolicy :

```
NAMESPACE                                                       NAME              BACKUP  RETENTION_POLICY
vao-preprod                                                     pg                set     60d
tumeplay-preprod                                                pg                set     60d
startup-domifa--metabase-preprod                                metabase          set     60d
secretariat-preprod                                             pg                set     60d
recosante-preprod                                               pg-api-node       set     60d
recosante-preprod                                               pg                set     60d
ozensemble-site-preprod                                         pg                set     60d
jardinmental-preprod                                            pg                set     60d
enfants-du-spectacle-preprod                                    pg-form           set     60d
enfants-du-spectacle-preprod                                    pg                set     60d
egapro-preprod                                                  pg                set     60d
carte-jeune-engage-preprod                                      pg                set     60d
carnets-preprod                                                 pg                set     60d
vao-persist-tests-securite-1gki4nz5                             pg                null    null
vao-main                                                        pg                null    null
vao-feat-408-fo-impossible-de-recevoir-un-nouveau-lie-34ij7jze  pg                null    null
vao-feat-385-f-back-office-comptes-visibilite-des-com-5p7fz1q3  pg                null    null
secretariat-fix-autoscale-prod-2wkaayu5                         pg                null    null
fce-preprod                                                     pg-strapi         null    null
fce-preprod                                                     pg-n8n            null    null
fce-preprod                                                     pg                null    null
env-1000jours-develop-91uqrtdu                                  pg                null    null
e2esdk-dev                                                      e2esdk-dev-cnpg2  null    null
domifa-chore-anonymisation-pipeline-4yrm09t1                    pg                null    null
cdtn-admin-preprod                                              pg                null    null
cdtn-admin-carolinebda-typo-2k8wx7n9                            pg                null    null
carte-jeune-engage-feat-user-enhancements-kw43xszb              pg                null    null
1000jours-preprod                                               pg                null    null
```

**Comment by igorrenquin** [comment]
@amir met à jour la liste des instances cnpg qui génére des sauvegardes superflux

**Comment by octomir** [comment]
@matmut7   sur l'environnement de dev, est-il possible de modifier par default la rétention policy ? 10j ou 5j ou 1j par ex ?
aussi l'activation de la compression afin de voir ce qu'on peut gagner (dans notre cas **bzip2**) ?

Définir une rétention policy pour les clusters cnpg de dev < 60j (le plus petit est le mieux)
(Option) activer la Compression

**Comment by billiwatio-octo** [comment]
- Les clusters qui n'ont pas de retention policy aujourd'hui n'ont tout simplement pas de backup activés (Pas de souci à ce niveau car nous sommes en dev)
- La compression est activé par défaut sur les cnpg dàprès @matmut7 
- A voir avec @igorrenquin si on modifier les rétentions policy  de 60 à 10j ou 5j ou 1j par exemple?  question budget ?

**Comment by billiwatio-octo** [comment]
@igorrenquin Propose de modifier les retention Policies à 7jrs pour le Dev .

**Comment by octomir** [comment]
Ce ticket est fermé pour un autre nouveau ticket sur la durée de rétention
