### ISSUE TITLE
[KUBERENETES] Montée de version

### ISSUE THREAD

**Issue by igorrenquin** [SocialGouv/support#583]
Dans le cadre de l'investigation sur la stabilité de la plateforme.

Réaliser la montée de version des clusters en version 1.27 afin de s'assurer de disposer des derniers correctifs pour identifier s'il ne s'agit pas d'un problème système.

**Comment by LucasBassoOcto** [comment]
A voir au retour de Antoine (28/05/2024) pour planifier une date de montée de version des différents clusters

**Comment by igorrenquin** [comment]
Mise à jour du cluster de DEV ☑

**Comment by gary-van-woerkens** [comment]
On peut clore ca ?

**Comment by igorrenquin** [comment]
Done 👍
