### ISSUE TITLE
Suivi décommissionement NATA

### ISSUE THREAD

**Issue by LucasBassoOcto** [SocialGouv/support#590]

**Comment by LucasBassoOcto** [comment]
En attente de la relance de Gary

**Comment by octomir** [comment]
Relancer yoan de numericité pour reprendre le site.

**Comment by gary-van-woerkens** [comment]
Numéricité va déployer le site de leur coté.
Nous attendons un retour de leur part sur le timing.

**Comment by igorrenquin** [comment]
Je viens de mettre en ligne une redirection permanente de l'url [nata.fabrique.social.gouv.fr](http://nata.fabrique.social.gouv.fr/) vers https://www.samusocial.paris/nata-lapplication

[MR](http://nata.fabrique.social.gouv.fr/)

Reste à terminer le nettoyage sur le cluster, sur github et dans infra-startup

**Comment by igorrenquin** [comment]
@igorrenquin suppression du workload sur kube + bootstrap

**Comment by gary-van-woerkens** [comment]
- [x] Les repos ont été archivés.
- [x] Les alertes (updown.io) ont été désactivées.

**Comment by igorrenquin** [comment]
Done 👍
