### ISSUE TITLE
[CI/CD] Tester la solution de Release Google

### ISSUE THREAD

**Issue by gary-van-woerkens** [SocialGouv/support#615]
https://github.com/googleapis/release-please

**Comment by matmut7** [comment]
Après un test, on ne peut pas déclencher des workflows à partir du merge de la PR release-please.
Même si c'est un dev avec des droits qui merge la PR, l'événement de push sur master provient toujours du bot release-please utilisant le `GITHUB_TOKEN`. Cet événement ne déclenche donc pas de workflows tels que la mise en prod.
