### ISSUE TITLE
CDTN ne dépend plus de recherche-entreprises

### ISSUE THREAD

**Issue by matmut7** [SocialGouv/support#622]
https://github.com/search?q=org%3ASocialGouv+recherche-entreprises&type=code

Est-ce qu'on peut décommissionner et archiver ? J'ai l'impression que egapro s'en sert aussi ?

**Comment by matmut7** [comment]
Toujours utilisé, au moins par egapro
https://mattermost.fabrique.social.gouv.fr/default/pl/umo5tunh47bdmgfqo8ret4p8hh

**Comment by gary-van-woerkens** [comment]
Conclusion, NON on ne peut pas supprimer `recherche-entreprises` tant que Egapro l'utilise.
