### ISSUE TITLE
[RECOSANTE] Metabase Recosanté

### ISSUE THREAD

**Issue by gary-van-woerkens** [SocialGouv/support#623]
Le dashboard de Recosante est tres lent, voir non fonctionnel.
Il faudrait investiguer pour comprendre d'ou vient la lenteur et si on peut corriger ca au niveau des requetes http.

Le dashboard en question:
https://metabase-recosante.fabrique.social.gouv.fr/dashboard/40-recosante-statistiques

---
- Peut etre virer ou corriger le Oauth Proxy

**Comment by matmut7** [comment]
🎉 https://github.com/SocialGouv/infra-apps/blob/master/startups/recosante/apps/metabase/envs/prod/templates/oauth2-proxy.configmap.yml#L12
