### ISSUE TITLE
SRE donner les accès sur scaleway projet stockage

### ISSUE THREAD

**Issue by igorrenquin** [SocialGouv/support#626]

**Comment by matmut7** [comment]
A priori mon accès est ok, je ne sais pas si tous les SRE ont le leur

**Comment by igorrenquin** [comment]
@igorrenquin donner les accés à Gary et Jo

**Comment by gary-van-woerkens** [comment]
Vérifier que Jo a les accès.

**Comment by igorrenquin** [comment]
@igorrenquin vérifier la présence de l'adresse proton de JO

**Comment by igorrenquin** [comment]
Done 👍
