### ISSUE TITLE
[IA] Mettre en place le setup des VMs IA sur OVH

### ISSUE THREAD

**Issue by gary-van-woerkens** [SocialGouv/support#638]
- [x] Création d'une instance via la console OVH
    - Selection du modèle: `B3-8`
    - Selection du localisation: `Gravelines`
    - Selection de l'image: `NVIDIA GPU Cloud (NGC)`
    - Selection de la clé SSH: `SRE`
    - Configuration de l'instance: par défaut
    - Selection du réseau: `Mode Public`
    - Selection de la période de facturation: `Horaire`
- [x] Installation de vLLM ([doc](https://docs.vllm.ai/en/stable/getting_started/cpu-installation.html))
- [x] Mise en place de `nginx-proxy` ([doc](https://codeberg.org/devthefuture/status-page#run-docker-compose-services))

**Comment by matmut7** [comment]
Déploiement en un clic avec un script + API OVH (python, pulumi, nodejs, etc.) + Github Actions
